### ISSUE TITLE
Не удается добавить конфиг файл

### ISSUE THREAD

**Issue by RazerElectra** [iamkuper/amnezia-youtube-config#2]
![2024-10-10_21-12-40](https://github.com/user-attachments/assets/9ce1e010-ee35-426c-a494-a29b5ee42d72)
народ при добавлении конфига на youtube пишет вот такое кто может подсказать как исправить ??

**Comment by iamkuper** [comment]
там чет битый видимо конфиг) не занимался им пока - чуть позже обновлю, адреса уже собрал всех серверов

**Comment by RazerElectra** [comment]
Дружище буду тебе признателен как займешься , на бравое дело стараешься
